#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#

#
# Environment Variables that need to be set to use this file
#
#   COMPOSE_PROJECT_NAME - This is used to ensure all chaincode containers are running on the same network
#                          as the peers, orderer, and ca. The only requirement is that this is set to
#                          some string and cannot be left blank. To match with the scripts use `fabric-fpc`.
#   PEER_CMD             - This variable indicates which peer binary should be used to start the peer.
#                          If regular peers are desired set this value to `peer`, if FPC peers are
#                          desired set this value to
#                          `/project/src/github.com/hyperledger-labs/fabric-private-chaincode/fabric/bin/peer.sh`

#
version: '2.1'

services:
  peer-base:
    environment:
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_basic
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - DOCKER_HOST=unix:///host/var/run/docker.sock
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
      - FABRIC_LOGGING_SPEC=${FABRIC_LOGGING_SPEC:-info}
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - PEER_CMD=${PEER_CMD}
      - ORDERER_ADDR=orderer.example.com:7050
      - CHANNEL_NAME=${CHANNEL_NAME}
    working_dir: /etc/hyperledger/configtx
    command: ${PEER_CMD} node start
    volumes:
        - /var/run/:/host/var/run/
        # Note: var run is required for docker daemon socket, see above DOCKER_HOST
        # and CORE_VM_ENDPOINT
        - ${DOCKERD_NETWORK_CONFIG}/config:/etc/hyperledger/configtx
        - ${DOCKERD_FPC_PATH}/examples:/project/src/github.com/hyperledger-labs/fabric-private-chaincode/examples
        - ${DOCKERD_FPC_PATH}/demo:/project/src/github.com/hyperledger-labs/fabric-private-chaincode/demo


  ca-base:
    image: hyperledger/fabric-ca:1.4.7
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.example.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.example.com_sk
    command: sh -c 'fabric-ca-server start -b admin:adminpw'

