# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0

dist: bionic

sudo: required
services:
  docker

addons:
  apt:
    packages:

go_import_path: github.com/hyperledger-labs/fabric-private-chaincode

env:
  global:

before_install:

script:
  # * test that it also properly in dev container
  #   (this should imply it also works on bare "metal"; in SIM mode only, though; but no SGX HW support in travis anyway?)
  - env DOCKER_QUIET_BUILD=1 DOCKER_BUILDKIT=0 make -C utils/docker run DOCKER_DEV_OPTIONAL_CMD='env DOCKER_QUIET_BUILD=1 DOCKER_BUILDKIT=0 make all clobber'
  #   Note: 
  #   - travis of couse does an implicit clobber but adding it here makes sure
  #     it works properly, also to make sure below is clean-slate
  #   - docker buildkit is not supported by travis, so override our default.
  #     (twice, once for each make invocation.)
  #   - to not run afoul of the travis log file limit we build docker stuff in quiet mode
  #     (which still should show log on errors ...)
