# Copyright IBM Corp. All Rights Reserved.
# Copyright Intel Corp. All Rights Reserved.

# Note: this is a tweaked version of './docker-compose.yaml' in hyperledger/blockchain-explorer.git

# SPDX-License-Identifier: Apache-2.0
version: '2'

volumes:
  pgdata:
  walletstore:

networks:
   basic:

services:
  explorerdb.example.com:
    image: hyperledger/explorer-db:latest
    container_name: explorerdb.example.com
    hostname: explorerdb.example.com
    environment:
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWORD=password
    volumes:
      # Note: below is a clone of 'app/persistence/fabric/postgreSQL/db/createdb.sh' from the blockchain-explorer repo
      - ./explorer/createdb.sh:/docker-entrypoint-initdb.d/createdb.sh
      - pgdata:/var/lib/postgresql/data
    networks:
      - basic

  explorer.example.com:
    image: hyperledger/explorer:latest
    container_name: explorer.example.com
    hostname: explorer.example.com
    environment:
      - DATABASE_HOST=explorerdb.example.com
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWD=password
      - DISCOVERY_AS_LOCALHOST=false
    volumes:
      - ./explorer/config.json:/opt/explorer/app/platform/fabric/config.json
      - ./explorer/connection-profile:/opt/explorer/app/platform/fabric/connection-profile
      - ./crypto-config:/tmp/crypto
      - walletstore:/opt/wallet
    # Note: below 30 sec sleep might be overly conservative but the original 16 was not enough in VirtualBox ...
    command: sh -c "sleep 30 && node /opt/explorer/main.js && tail -f /dev/null"
    ports:
      - 8090:8080
    networks:
      - basic
