# Copyright IBM Corp. All Rights Reserved.
# Copyright 2020 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

version: '3'

services:
  #  org1
  ecc.peer0.org1.example.com:
    container_name: ecc.peer0.org1.example.com
    hostname: ecc.peer0.org1.example.com
    image: fpc/fpc-echo
    environment:
      - CHAINCODE_SERVER_ADDRESS=ecc.peer0.org1.example.com:9999
      - CHAINCODE_PKG_ID=${ORG1_ECC_PKG_ID}
      - FABRIC_LOGGING_SPEC=${FABRIC_LOGGING_SPEC:-DEBUG}
    networks:
      - default

  ercc.peer0.org1.example.com:
    container_name: ercc.peer0.org1.example.com
    hostname: ercc.peer0.org1.example.com
    image: fpc/ercc
    environment:
      - CHAINCODE_SERVER_ADDRESS=ercc.peer0.org1.example.com:9999
      - CHAINCODE_PKG_ID=${ORG1_ERCC_PKG_ID}
      - FABRIC_LOGGING_SPEC=${FABRIC_LOGGING_SPEC:-DEBUG}
    networks:
      - default

  # org2
  ecc.peer0.org2.example.com:
    container_name: ecc.peer0.org2.example.com
    hostname: ecc.peer0.org2.example.com
    image: fpc/fpc-echo
    environment:
      - CHAINCODE_SERVER_ADDRESS=ecc.peer0.org2.example.com:9999
      - CHAINCODE_PKG_ID=${ORG2_ECC_PKG_ID}
      - FABRIC_LOGGING_SPEC=${FABRIC_LOGGING_SPEC:-DEBUG}
    networks:
      - default

  ercc.peer0.org2.example.com:
    container_name: ercc.peer0.org2.example.com
    hostname: ercc.peer0.org2.example.com
    image: fpc/ercc
    environment:
      - CHAINCODE_SERVER_ADDRESS=ercc.peer0.org2.example.com:9999
      - CHAINCODE_PKG_ID=${ORG2_ERCC_PKG_ID}
      - FABRIC_LOGGING_SPEC=${FABRIC_LOGGING_SPEC:-DEBUG}
    networks:
      - default

networks:
  default:
    external:
      name: net_test
